export interface IslamicCity {
  slug: string;
  name: string;
  nameUrdu: string;
  province: string;
  country: string;
  latitude: number;
  longitude: number;
  population: string;
  timezone: string;
  /** Unique local context for SEO — avoids scaled-content abuse */
  localContext: string;
  notableMosques: string[];
  prayerMethodNote: string;
}

export const PAKISTAN_CITIES: IslamicCity[] = [
  {
    slug: 'lahore',
    name: 'Lahore',
    nameUrdu: 'لاہور',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 31.5204,
    longitude: 74.3587,
    population: '13+ million',
    timezone: 'Asia/Karachi',
    localContext:
      'Lahore, the cultural heart of Pakistan, hosts the historic Badshahi Mosque and Data Darbar shrine. Prayer times here follow the University of Islamic Sciences, Karachi method, widely adopted across Punjab.',
    notableMosques: ['Badshahi Mosque', 'Data Darbar', 'Wazir Khan Mosque', 'Grand Jamia Mosque'],
    prayerMethodNote: 'Karachi calculation method (method 1) — standard across Punjab province.',
  },
  {
    slug: 'karachi',
    name: 'Karachi',
    nameUrdu: 'کراچی',
    province: 'Sindh',
    country: 'Pakistan',
    latitude: 24.8607,
    longitude: 67.0011,
    population: '16+ million',
    timezone: 'Asia/Karachi',
    localContext:
      'Karachi, Pakistan\'s largest metropolis and economic hub, is home to Tooba Mosque (Gol Masjid) and Masjid-e-Tooba. As a coastal city, Maghrib times shift noticeably with sunset over the Arabian Sea.',
    notableMosques: ['Tooba Mosque', 'Masjid-e-Tooba', 'Memon Masjid', 'Jinnah Mosque'],
    prayerMethodNote: 'Karachi calculation method — the origin city of this method, used nationwide.',
  },
  {
    slug: 'islamabad',
    name: 'Islamabad',
    nameUrdu: 'اسلام آباد',
    province: 'Federal Capital',
    country: 'Pakistan',
    latitude: 33.6844,
    longitude: 73.0479,
    population: '2+ million',
    timezone: 'Asia/Karachi',
    localContext:
      'Islamabad, Pakistan\'s planned capital nestled against the Margalla Hills, features the iconic Faisal Mosque — one of the largest mosques in the world. Prayer times are slightly earlier than southern cities due to higher latitude.',
    notableMosques: ['Faisal Mosque', 'Shah Faisal Mosque', 'Lal Masjid', 'Jamia Masjid'],
    prayerMethodNote: 'Karachi method with Hanafi Asr calculation — standard for Islamabad and Rawalpindi twin cities.',
  },
  {
    slug: 'rawalpindi',
    name: 'Rawalpindi',
    nameUrdu: 'راولپنڈی',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 33.5651,
    longitude: 73.0169,
    population: '2.1+ million',
    timezone: 'Asia/Karachi',
    localContext:
      'Rawalpindi, the garrison city adjacent to Islamabad, has a rich military and commercial history. Jamia Masjid Raja Bazaar is a central landmark. Prayer times mirror Islamabad due to proximity.',
    notableMosques: ['Jamia Masjid Raja Bazaar', 'Lal Haveli Mosque', 'Army Mosque'],
    prayerMethodNote: 'Same calculation as Islamabad — Karachi method, Hanafi school for Asr.',
  },
  {
    slug: 'faisalabad',
    name: 'Faisalabad',
    nameUrdu: 'فیصل آباد',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 31.4504,
    longitude: 73.135,
    population: '3.2+ million',
    timezone: 'Asia/Karachi',
    localContext:
      'Faisalabad, formerly Lyallpur, is Punjab\'s textile capital. The Clock Tower (Ghanta Ghar) area has several historic mosques. The city\'s flat terrain means consistent prayer times year-round.',
    notableMosques: ['Jinnah Mosque Faisalabad', 'Clock Tower Mosque', 'Madina Mosque'],
    prayerMethodNote: 'Karachi method — standard across central Punjab industrial belt.',
  },
  {
    slug: 'multan',
    name: 'Multan',
    nameUrdu: 'ملتان',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 30.1575,
    longitude: 71.5249,
    population: '1.9+ million',
    timezone: 'Asia/Karachi',
    localContext:
      'Multan, the City of Saints, is one of the oldest cities in South Asia. The historic Multan Fort area and shrines of Bahauddin Zakariya and Shah Rukn-e-Alam define its spiritual landscape.',
    notableMosques: ['Jamia Mosque Multan', 'Eid Gah Mosque', 'Shah Rukn-e-Alam Shrine Mosque'],
    prayerMethodNote: 'Karachi method — southern Punjab standard, slightly earlier Maghrib than northern cities.',
  },
  {
    slug: 'gujranwala',
    name: 'Gujranwala',
    nameUrdu: 'گوجرانوالہ',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 32.1877,
    longitude: 74.1945,
    population: '2.8+ million',
    timezone: 'Asia/Karachi',
    localContext:
      'Gujranwala is a major industrial city in northern Punjab, known for its steel and ceramics industries. The city has a strong tradition of Friday congregational prayers at central mosques.',
    notableMosques: ['Jamia Mosque Gujranwala', 'Eid Gah Gujranwala', 'Railway Mosque'],
    prayerMethodNote: 'Karachi method — northern Punjab standard.',
  },
  {
    slug: 'peshawar',
    name: 'Peshawar',
    nameUrdu: 'پشاور',
    province: 'Khyber Pakhtunkhwa',
    country: 'Pakistan',
    latitude: 34.0151,
    longitude: 71.5249,
    population: '2.3+ million',
    timezone: 'Asia/Karachi',
    localContext:
      'Peshawar, the gateway to Khyber Pass, is one of the oldest living cities in Asia. Mahabat Khan Mosque in the old city is a Mughal-era masterpiece. KPK follows the same Karachi method as Punjab.',
    notableMosques: ['Mahabat Khan Mosque', 'Masjid Qasim Ali Khan', 'Jamia Masjid Peshawar'],
    prayerMethodNote: 'Karachi method — used across KPK province.',
  },
  {
    slug: 'sialkot',
    name: 'Sialkot',
    nameUrdu: 'سیالکوٹ',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 32.4945,
    longitude: 74.5229,
    population: '920,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Sialkot, birthplace of Allama Iqbal, is a major export hub near the Kashmir border. The city\'s sports goods and surgical instruments industries support a vibrant Muslim community.',
    notableMosques: ['Jamia Mosque Sialkot', 'Iqbal Manzil Mosque', 'Cantt Mosque'],
    prayerMethodNote: 'Karachi method — northeastern Punjab.',
  },
  {
    slug: 'quetta',
    name: 'Quetta',
    nameUrdu: 'کوئٹہ',
    province: 'Balochistan',
    country: 'Pakistan',
    latitude: 30.1798,
    longitude: 66.975,
    population: '1.2+ million',
    timezone: 'Asia/Karachi',
    localContext:
      'Quetta, capital of Balochistan at 1,680m elevation, has distinct seasonal prayer time variations. The city serves as a hub for Hazara and Pashtun communities with diverse mosque traditions.',
    notableMosques: ['Jamia Masjid Quetta', 'Masjid Usmani', 'Hazara Town Mosque'],
    prayerMethodNote: 'Karachi method — high altitude causes earlier Fajr and later Maghrib in summer.',
  },
  {
    slug: 'hyderabad',
    name: 'Hyderabad',
    nameUrdu: 'حیدرآباد',
    province: 'Sindh',
    country: 'Pakistan',
    latitude: 25.396,
    longitude: 68.3578,
    population: '1.7+ million',
    timezone: 'Asia/Karachi',
    localContext:
      'Hyderabad, Sindh\'s second-largest city on the Indus River, has a rich Sufi heritage. Pacco Qillo (Hyderabad Fort) area hosts historic mosques dating to the Talpur era.',
    notableMosques: ['Jamia Mosque Hyderabad', 'Pacco Qillo Mosque', 'Eid Gah Hyderabad'],
    prayerMethodNote: 'Karachi method — southern Sindh, similar timings to Karachi.',
  },
  {
    slug: 'bahawalpur',
    name: 'Bahawalpur',
    nameUrdu: 'بہاولپور',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 29.3956,
    longitude: 71.6836,
    population: '780,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Bahawalpur, a princely state until 1955, features the magnificent Abbasi Mosque and Noor Mahal. The Cholistan Desert proximity means hot summers with extended daylight hours.',
    notableMosques: ['Abbasi Mosque', 'Jamia Mosque Bahawalpur', 'Derawar Mosque'],
    prayerMethodNote: 'Karachi method — southern Punjab desert region.',
  },
  {
    slug: 'sargodha',
    name: 'Sargodha',
    nameUrdu: 'سرگودھا',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 32.0836,
    longitude: 72.6711,
    population: '660,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Sargodha, known as the "California of Pakistan" for its citrus orchards, is a major Pakistan Air Force base city. Central Punjab location gives moderate prayer times year-round.',
    notableMosques: ['PAF Mosque Sargodha', 'Jamia Mosque Sargodha', 'Cantonment Mosque'],
    prayerMethodNote: 'Karachi method — central Punjab.',
  },
  {
    slug: 'sukkur',
    name: 'Sukkur',
    nameUrdu: 'سکھر',
    province: 'Sindh',
    country: 'Pakistan',
    latitude: 27.7052,
    longitude: 68.8574,
    population: '500,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Sukkur sits on the west bank of the Indus River, home to the historic Lansdowne Bridge and Sadhu Bela temple island. The city\'s riverfront mosques serve a close-knit trading community.',
    notableMosques: ['Jamia Mosque Sukkur', 'Minara Mosque', 'Rohri Mosque'],
    prayerMethodNote: 'Karachi method — upper Sindh.',
  },
  {
    slug: 'larkana',
    name: 'Larkana',
    nameUrdu: 'لاڑکانہ',
    province: 'Sindh',
    country: 'Pakistan',
    latitude: 27.5600,
    longitude: 68.2262,
    population: '490,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Larkana, in interior Sindh, is near Mohenjo-daro archaeological site. The Bhutto family\'s ancestral city has strong Shia and Sunni mosque communities.',
    notableMosques: ['Jamia Mosque Larkana', 'Imambargah Larkana', 'Garhi Khuda Bakhsh Mosque'],
    prayerMethodNote: 'Karachi method — interior Sindh.',
  },
  {
    slug: 'sheikhupura',
    name: 'Sheikhupura',
    nameUrdu: 'شیخوپورہ',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 31.7167,
    longitude: 73.9853,
    population: '591,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Sheikhupura, an industrial city between Lahore and Gujranwala, is known for Hiran Minar (Mughal-era monument). Prayer times closely match Lahore.',
    notableMosques: ['Jamia Mosque Sheikhupura', 'Hiran Minar Mosque', 'Industrial Area Mosque'],
    prayerMethodNote: 'Karachi method — matches Lahore timings.',
  },
  {
    slug: 'gujrat',
    name: 'Gujrat',
    nameUrdu: 'گجرات',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 32.5742,
    longitude: 74.0754,
    population: '390,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Gujrat, on the Chenab River, is famous for ceramics and fan manufacturing. The city has produced notable Islamic scholars and maintains active mosque communities.',
    notableMosques: ['Jamia Mosque Gujrat', 'Chenab Bridge Mosque', 'Cantonment Mosque'],
    prayerMethodNote: 'Karachi method — northern Punjab Chenab belt.',
  },
  {
    slug: 'jhelum',
    name: 'Jhelum',
    nameUrdu: 'جہلم',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 32.9345,
    longitude: 73.731,
    population: '190,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Jhelum, on the right bank of the Jhelum River, has a historic cantonment and produces many Pakistan Army officers. The city\'s mosques serve both civilian and military communities.',
    notableMosques: ['Jamia Mosque Jhelum', 'Cantonment Mosque', 'River View Mosque'],
    prayerMethodNote: 'Karachi method — northern Punjab.',
  },
  {
    slug: 'sahiwal',
    name: 'Sahiwal',
    nameUrdu: 'ساہیوال',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 30.6682,
    longitude: 73.1114,
    population: '390,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Sahiwal, a major agricultural centre in central Punjab, is known for its cattle market and fertile farmland. The city\'s mosques are central to rural-urban community life.',
    notableMosques: ['Jamia Mosque Sahiwal', 'Eid Gah Sahiwal', 'Harappa Road Mosque'],
    prayerMethodNote: 'Karachi method — central Punjab agricultural belt.',
  },
  {
    slug: 'abbottabad',
    name: 'Abbottabad',
    nameUrdu: 'ایبٹ آباد',
    province: 'Khyber Pakhtunkhwa',
    country: 'Pakistan',
    latitude: 34.1688,
    longitude: 73.2215,
    population: '330,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Abbottabad, a hill station at 1,260m in the Hazara region, has cooler climate and distinct seasonal prayer variations. The city is a gateway to northern tourist destinations.',
    notableMosques: ['Jamia Mosque Abbottabad', 'Ilyasi Mosque', 'Hazara University Mosque'],
    prayerMethodNote: 'Karachi method — higher altitude, earlier summer Fajr.',
  },
  {
    slug: 'mardan',
    name: 'Mardan',
    nameUrdu: 'مردان',
    province: 'Khyber Pakhtunkhwa',
    country: 'Pakistan',
    latitude: 34.1983,
    longitude: 72.0458,
    population: '360,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Mardan is the second-largest city in KPK and an educational hub with Abdul Wali Khan University. The city has a strong Deobandi and Barelvi mosque tradition.',
    notableMosques: ['Jamia Mosque Mardan', 'Takht Bhai Mosque', 'University Mosque'],
    prayerMethodNote: 'Karachi method — KPK central region.',
  },
  {
    slug: 'mingora',
    name: 'Mingora',
    nameUrdu: 'مینگورہ',
    province: 'Khyber Pakhtunkhwa',
    country: 'Pakistan',
    latitude: 34.7717,
    longitude: 72.3603,
    population: '330,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Mingora is the largest city in Swat Valley, known for its natural beauty and Malala Yousafzai\'s hometown. The Swat region has unique mosque architecture blending Pashtun and Mughal styles.',
    notableMosques: ['Jamia Mosque Mingora', 'Saidu Sharif Mosque', 'Swat Central Mosque'],
    prayerMethodNote: 'Karachi method — Swat valley, higher latitude.',
  },
  {
    slug: 'mirpur',
    name: 'Mirpur',
    nameUrdu: 'میرپور',
    province: 'Azad Kashmir',
    country: 'Pakistan',
    latitude: 33.1484,
    longitude: 73.7519,
    population: '125,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Mirpur (Azad Kashmir) is known as "Little England" due to diaspora links. Mangla Dam nearby makes it a scenic city with active mosque communities serving local and diaspora families.',
    notableMosques: ['Jamia Mosque Mirpur', 'Mangla Mosque', 'Mirpur Cantonment Mosque'],
    prayerMethodNote: 'Karachi method — Azad Kashmir standard.',
  },
  {
    slug: 'okara',
    name: 'Okara',
    nameUrdu: 'اوکاڑہ',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 30.8081,
    longitude: 73.4458,
    population: '300,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Okara, on the Ravi River, is a major military cantonment and agricultural district. The Okara Military Farms area has historic mosque communities.',
    notableMosques: ['Jamia Mosque Okara', 'Cantonment Mosque', 'Ravi River Mosque'],
    prayerMethodNote: 'Karachi method — central Punjab.',
  },
  {
    slug: 'dera-ghazi-khan',
    name: 'Dera Ghazi Khan',
    nameUrdu: 'ڈیرہ غازی خان',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 30.0561,
    longitude: 70.6348,
    population: '380,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Dera Ghazi Khan, at the junction of Punjab, Balochistan, and KPK, is a gateway city to tribal areas. Hot desert climate means extended summer daylight and later Isha times.',
    notableMosques: ['Jamia Mosque DG Khan', 'Fort Mosque', 'Sakhi Sarwar Shrine Mosque'],
    prayerMethodNote: 'Karachi method — southern Punjab gateway.',
  },
  {
    slug: 'murree',
    name: 'Murree',
    nameUrdu: 'مری',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 33.907,
    longitude: 73.3903,
    population: '50,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Murree, a popular hill station at 2,291m, attracts tourists year-round. Prayer times differ significantly from Islamabad due to altitude — Fajr is notably earlier in summer.',
    notableMosques: ['Murree Mall Road Mosque', 'Kashmir Point Mosque', 'Patriata Mosque'],
    prayerMethodNote: 'Karachi method — high altitude hill station, seasonal variation.',
  },
  {
    slug: 'chiniot',
    name: 'Chiniot',
    nameUrdu: 'چنیوٹ',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 31.7204,
    longitude: 72.9784,
    population: '280,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Chiniot on the Chenab River is world-famous for exquisite wooden furniture and craftsmanship. The Shahi Mosque Chiniot is an architectural gem built in 1655.',
    notableMosques: ['Shahi Mosque Chiniot', 'Jamia Mosque Chiniot', 'Chenab Riverside Mosque'],
    prayerMethodNote: 'Karachi method — central Punjab Chenab region.',
  },
  {
    slug: 'swat',
    name: 'Swat',
    nameUrdu: 'سوات',
    province: 'Khyber Pakhtunkhwa',
    country: 'Pakistan',
    latitude: 35.2227,
    longitude: 72.4258,
    population: '230,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Swat Valley, the "Switzerland of Pakistan", has Buddhist heritage alongside Islamic traditions. Butkara Stupa and Mingora mosques coexist in this scenic northern region.',
    notableMosques: ['Central Mosque Swat', 'Mingora Grand Mosque', 'Kalam Valley Mosque'],
    prayerMethodNote: 'Karachi method — northern KPK, earliest Fajr in Pakistan.',
  },
  {
    slug: 'taxila',
    name: 'Taxila',
    nameUrdu: 'ٹیکسلا',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 33.7461,
    longitude: 72.8397,
    population: '120,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Taxila, a UNESCO World Heritage Site with ancient Buddhist ruins, is now a university town. The Taxila Museum area has mosques serving students and archaeologists alike.',
    notableMosques: ['Jamia Mosque Taxila', 'University Mosque', 'Khanpur Mosque'],
    prayerMethodNote: 'Karachi method — matches Rawalpindi/Islamabad.',
  },
  {
    slug: 'mansehra',
    name: 'Mansehra',
    nameUrdu: 'مانسہرہ',
    province: 'Khyber Pakhtunkhwa',
    country: 'Pakistan',
    latitude: 34.3333,
    longitude: 73.2,
    population: '110,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Mansehra on the Karakoram Highway is the gateway to Gilgit-Baltistan and China. The city serves as a rest stop for travellers and has active truck-driver mosque communities.',
    notableMosques: ['Jamia Mosque Mansehra', 'Karakoram Highway Mosque', 'Baffa Mosque'],
    prayerMethodNote: 'Karachi method — Hazara region KPK.',
  },
  {
    slug: 'nawabshah',
    name: 'Nawabshah',
    nameUrdu: 'نوابشاہ',
    province: 'Sindh',
    country: 'Pakistan',
    latitude: 26.2442,
    longitude: 68.41,
    population: '280,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Nawabshah (Shaheed Benazirabad) is a major cotton and sugarcane hub in central Sindh. The city\'s agricultural economy supports rural mosque networks across the district.',
    notableMosques: ['Jamia Mosque Nawabshah', 'Sakrand Mosque', 'Qazi Ahmed Mosque'],
    prayerMethodNote: 'Karachi method — central Sindh.',
  },
  {
    slug: 'wah-cantt',
    name: 'Wah Cantt',
    nameUrdu: 'واہ کینٹ',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 33.7733,
    longitude: 72.7458,
    population: '380,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Wah Cantt, home to Pakistan Ordnance Factories, is a planned industrial city between Rawalpindi and Taxila. The city has well-organised mosque communities for factory workers.',
    notableMosques: ['POF Mosque Wah', 'Jamia Mosque Wah Cantt', 'Lalarukh Mosque'],
    prayerMethodNote: 'Karachi method — matches Islamabad/Rawalpindi.',
  },
  {
    slug: 'sadiqabad',
    name: 'Sadiqabad',
    nameUrdu: 'صادق آباد',
    province: 'Punjab',
    country: 'Pakistan',
    latitude: 28.3081,
    longitude: 70.1306,
    population: '270,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Sadiqabad in southern Punjab near the Sindh border is a trading city on the Indus Highway. Its location means prayer times align closely with Bahawalpur and Rahim Yar Khan.',
    notableMosques: ['Jamia Mosque Sadiqabad', 'Indus Highway Mosque', 'Khanpur Mosque'],
    prayerMethodNote: 'Karachi method — southern Punjab border region.',
  },
  {
    slug: 'kotri',
    name: 'Kotri',
    nameUrdu: 'کوٹری',
    province: 'Sindh',
    country: 'Pakistan',
    latitude: 25.3656,
    longitude: 68.3083,
    population: '100,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Kotri, across the Indus from Hyderabad, is a major railway junction. The Kotri Barrage area has mosques serving railway workers and river communities.',
    notableMosques: ['Jamia Mosque Kotri', 'Railway Station Mosque', 'Barrage Mosque'],
    prayerMethodNote: 'Karachi method — matches Hyderabad.',
  },
  {
    slug: 'chaman',
    name: 'Chaman',
    nameUrdu: 'چمن',
    province: 'Balochistan',
    country: 'Pakistan',
    latitude: 30.921,
    longitude: 66.4597,
    population: '100,000+',
    timezone: 'Asia/Karachi',
    localContext:
      'Chaman is the border town with Afghanistan, a major trade crossing. The city\'s mosques serve Pashtun traders and border communities with distinct cultural traditions.',
    notableMosques: ['Jamia Mosque Chaman', 'Border Market Mosque', 'Baba Sahib Mosque'],
    prayerMethodNote: 'Karachi method — Balochistan border, hot summers.',
  },
];

export function getCityBySlug(slug: string): IslamicCity | undefined {
  return PAKISTAN_CITIES.find((c) => c.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return PAKISTAN_CITIES.map((c) => c.slug);
}
